spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://localhost:3307/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver

    test2:
      jdbc-url: jdbc:mysql://localhost:3308/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver

    test3:
      jdbc-url: jdbc:mysql://localhost:3309/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jta:
    enabled: true # JTA 트랜잭션 활성화
    max-active: 3 # 최대 활성 트랜잭션 수
