spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://localhost:3307/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver

    test2:
      jdbc-url: jdbc:mysql://localhost:3308/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver

    test3:
      jdbc-url: jdbc:mysql://localhost:3309/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver